spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Umbra*1997
  jpa:
    show-slq: 'true'
    hibernate:
      ddl-auto: update